### ISSUE TITLE
Unable to go on duty

### ISSUE THREAD

**Issue by DonnyFennLive** [DvScriptsSK/qb-sheriffjob#1]
When going on duty it auto place you in Off Duty again

**Comment by KopnickyDavid** [comment]
I will look into it and fix.
If you have any other questions you can go to my discord server

**Comment by KopnickyDavid** [comment]
I see the issue

**Comment by DonnyFennLive** [comment]
is the job going to be updated with the issue fixed?

**Comment by KopnickyDavid** [comment]
Yes this week

**Comment by DonnyFennLive** [comment]
nice

**Comment by YordiGhurt** [comment]
on duty is not fixed? ;)
We have the Problem

**Comment by KopnickyDavid** [comment]
It was fixed but whole
job will be updated

**Comment by lak1z-azk** [comment]
Seems that this issue still persists  :/ any ETA date for fix?

**Comment by lak1z-azk** [comment]
Seems that I found an issue. There is a duplicating code line for going on duty which just moves back to off duty. So here is what I done to achieve a normal "On Duty":
1. In client/job.lua there is a duplicating lines 
![image](https://github.com/DvScriptsSK/qb-sheriffjob/assets/100957521/cd51a6b9-f731-4bac-8024-8a2fef919d54)

I have just deleted them. 
2. Then below the "Toggle Duty in an event"  i have just deleted one line "onDuty = not onDuty"
![image](https://github.com/DvScriptsSK/qb-sheriffjob/assets/100957521/f4aef8fa-cf0f-4a47-aaa1-285df4307441)
in screenshot is visible which line can be deleted. 

3.Then I went to main.lua and scrolled down to the 103 line (yes I was sitting before and trying to find an issue why it is going on duty and back to off duty .... ) 
![image](https://github.com/DvScriptsSK/qb-sheriffjob/assets/100957521/4b098497-1891-4315-a875-9753fd784b9d)

And I have commented 108 and 109 line. As you can see how the commented lines looks like. 

Sorry, just wanted to help with the fix for that, as I haven't seen any updates on this script for 2 years.

**Comment by SANCTISGROUP** [comment]
> Seems that I found an issue. There is a duplicating code line for going on duty which just moves back to off duty. So here is what I done to achieve a normal "On Duty":
> 
> 1. In client/job.lua there is a duplicating lines
>    ![image](https://user-images.githubusercontent.com/100957521/260325974-cd51a6b9-f731-4bac-8024-8a2fef919d54.png)
> 
> I have just deleted them. 2. Then below the "Toggle Duty in an event" i have just deleted one line "onDuty = not onDuty" ![image](https://user-images.githubusercontent.com/100957521/260326015-f4aef8fa-cf0f-4a47-aaa1-285df4307441.png) in screenshot is visible which line can be deleted.
> 
> 3.Then I went to main.lua and scrolled down to the 103 line (yes I was sitting before and trying to find an issue why it is going on duty and back to off duty .... ) ![image](https://user-images.githubusercontent.com/100957521/260326076-4b098497-1891-4315-a875-9753fd784b9d.png)
> 
> And I have commented 108 and 109 line. As you can see how the commented lines looks like.
> 
> Sorry, just wanted to help with the fix for that, as I haven't seen any updates on this script for 2 years.

Work.
